# Generated by Django 3.2.13 on 2023-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.CharField(max_length=500)),
                ('curries', models.CharField(max_length=500)),
                ('dal', models.CharField(max_length=500)),
                ('chips', models.CharField(max_length=500)),
                ('curd', models.CharField(max_length=500)),
                ('juice', models.CharField(max_length=500)),
                ('salad', models.CharField(max_length=500)),
                ('pickle', models.CharField(max_length=500)),
                ('dessert', models.CharField(max_length=400)),
            ],
        ),
    ]
