# Generated by Django 3.2.13 on 2023-08-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230820_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='session',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
