# Generated by Django 3.2.13 on 2023-08-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_daymenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.CharField(max_length=500)),
                ('curries', models.CharField(max_length=500)),
                ('dal', models.CharField(max_length=500)),
                ('chips', models.BooleanField(default=True)),
                ('curd', models.BooleanField(default=True)),
                ('juice', models.CharField(max_length=500)),
                ('salad', models.CharField(max_length=500)),
                ('pickle', models.CharField(max_length=500)),
                ('dessert', models.CharField(max_length=400)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.day')),
            ],
        ),
        migrations.DeleteModel(
            name='DayMenu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
