# Generated by Django 3.2.13 on 2023-08-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_snacks_snack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snack',
            new_name='Snacks',
        ),
    ]
