# Generated by Django 3.2.13 on 2023-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_rename_snack_snacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='juice',
            field=models.CharField(max_length=200),
        ),
    ]
